name: xylophone
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.20.1
  # Use Audioplayers dependency version 0.17.4

  cupertino_icons: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/